### ISSUE TITLE
Crash on startup with version 1.0.2

### ISSUE THREAD

**Issue by fullskele** [WinDanesz/WizardryNecromancersDelight#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

The game crashes moments after the game window pops up during loading.

### Expected behaviour

The game was expected to complete loading, etc.

### Steps to reproduce

1. Launch the game in a modpack
2. Wait 1-2 minutes

### Crashlog

https://gist.github.com/fullskele/687ee40db3f29c3d4d159fd7b469a073

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

1.0.2

### Forge version

1.12.2 - 14.23.5.2859

**Comment by pacjack** [comment]
I have the same thing happening to my modpack, but use the 1.0.1 mod version.

**Comment by WinDanesz** [comment]
Should be fixed in the newer versions
